### PR TITLE
changed youtube logo

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Review by netux — CHANGES_REQUESTED** [review]
Good idea! Though I don't really like how the DeArrow logo is cut off.
Maybe that logo could be made smaller? Or the YT logo could be made smaller, leaving some space for the DeArrow logo to span outside YT's logo?

**Comment by Bluscream** [comment]
HASS Agent_2g900ZQzmL

to me it looks absolutely fine and makes it easy to differentiate between the non-dearrow and the dearrow versions.
If you want something else, you can find high quality versions of the youtube and dearrow logos on google

**Comment by netux** [comment]
I was thinking of something similar to the "Fork with full SponsorBlock" icon on your image: the DeArrow icon being placed similarly to the demonetized icon, and it being shown fully instead of cutting off to the right and bottom (showing that the image is rectangular - looks a bit ugly)

**Comment by Bluscream** [comment]
source files i used:
- https://logodownload.org/wp-content/uploads/2014/10/youtube-logo-5-2.png
- https://dearrow.ajay.app/logo.svg

i overlayed them in paint.net using the svg addon for it

**Comment by netux** [comment]
Right, I was thinking of something like this

youtube_dearrow

Notice how the DeArrow icon is shown in full.

**Comment by netux** [comment]
Alternatively, something like this looks nice too. With the YT logo being shrunk down:

youtube_dearrow2

**Comment by Bluscream** [comment]
yours looks good. if you commit that i will update my repo accordingly

**Comment by netux** [comment]
> yours looks good. if you commit that i will update my repo accordingly

I'm currently in the middle of implementing #5, which changes the code base quite a log. So I will do it after 🙂.

**Comment by netux** [comment]
... not sure at all why GitHub thought I merged this, because I definitely didn't. This PR also has no commits now, apparently?

Whatever, I will add the new logo next release.

**Pull request merged**
